# Generated by Django 3.2 on 2022-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('business_hours', models.CharField(max_length=100)),
                ('regular_holiday', models.CharField(max_length=20)),
                ('wifi', models.CharField(choices=[('yes', 'あり'), ('no', 'なし')], max_length=10)),
                ('power', models.CharField(choices=[('yes', 'あり'), ('no', 'なし')], max_length=10)),
                ('access', models.CharField(max_length=100)),
                ('hp', models.CharField(max_length=100)),
            ],
        ),
    ]
