# Generated by Django 3.2 on 2022-06-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20220528_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='power',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='tel',
        ),
    ]
