# Generated by Django 3.2 on 2022-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20220604_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='regular_holiday',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='wifi',
            field=models.CharField(max_length=100),
        ),
    ]
